---
title: "book_seller"
author: "Christa Spieth"
date: "1/15/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## import file
```{r}
library(data.table)
library(dplyr)
library(caret)
library(zoo)
library(lubridate)
library(lme4)

book <- fread("orders.csv")
train <- fread("booktrain.csv")

# data type change
ref_date <- as.Date("2014-08-01")
book$orddate <- as.Date(book$orddate, format = "%d%B%Y")
book$days <- ref_date - book$orddate
book$months <- (as.yearmon(ref_date, format = "%d%B%Y")-as.yearmon(book$orddate, format = "%d%B%Y")) * 12
book$years <- year(ref_date) - year(book$orddate)

# feature creation
cat_dum <- dummy(factor(book$category))
book <- cbind(book, cat_dum)

cat_agg <- aggregate(x=book[,10:38],by=list(book$id),FUN = sum)

book <- book[,.(totQty = sum(qty), qty.m = mean(qty), totPrice = sum(price), logPrice = mean(log(price)), price.m = mean(price), numOrd = .N, days_rec = min(days), months_rec = min(months), years_rec = min(years),
                days_old = max(days), months_old = max(months), years_old = max(years)), by=.(id)]

book <- cbind(book,cat_agg[,-1])

book$logPrice[book$logPrice == -Inf] <- 0

# merge features with training set
merged <- merge(book,train,by="id")
merged$purchase <- ifelse(merged$logtarg!=0,1,0)
```

## logistic regression
```{r}
log1 <- glm(purchase~.,data = merged[,-c(1,38)],family = binomial)
step(log1)

log2 <- glm(formula = purchase ~ date + `6` + `8` + `10` + 
              `12` + `19` + `20` + `23` + `30` + `38`, family = binomial, 
            data = merged)
summary(log2)
```

## linear regression
```{r}
lm1 <- lm(formula = logtarg ~ . + I(days_old-days_rec) + I(months_old-months_rec) + I(years_old-years_rec), data = merged[merged$logtarg!=0,-c(1,44)])
summary(lm1)

step(lm1)
lm2 <- lm(formula = logtarg ~ totPrice + price.m + numOrd + months_rec + 
    years_rec + days_old + `7` + `14` + `20` + `26` + `27` + 
    `35` + `40` + `50`, data = merged[merged$logtarg != 0, -c(1, 
    44)])

summary(lm2)
```
